// Autogenerated from Pigeon (v26.1.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsMessages(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsMessages(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsMessages(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashMessages(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashMessages(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashMessages(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// The type of callback URL matching to use.
enum CallbackType: Int {
  /// Match by custom URL scheme (e.g., `myapp://...`).
  case customScheme = 0
  /// Match by HTTPS host and path (Universal Links).
  case https = 1
}

/// Configuration for how to match callback URLs.
///
/// Generated class from Pigeon that represents data sent in messages.
struct CallbackConfigMessage: Hashable {
  /// The type of callback matching.
  var type: CallbackType
  /// The custom URL scheme (for [CallbackType.customScheme]).
  var scheme: String? = nil
  /// The HTTPS host (for [CallbackType.https]).
  var host: String? = nil
  /// The HTTPS path (for [CallbackType.https]).
  var path: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> CallbackConfigMessage? {
    let type = pigeonVar_list[0] as! CallbackType
    let scheme: String? = nilOrValue(pigeonVar_list[1])
    let host: String? = nilOrValue(pigeonVar_list[2])
    let path: String? = nilOrValue(pigeonVar_list[3])

    return CallbackConfigMessage(
      type: type,
      scheme: scheme,
      host: host,
      path: path
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      scheme,
      host,
      path,
    ]
  }
  static func == (lhs: CallbackConfigMessage, rhs: CallbackConfigMessage) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

/// Request to start a redirect-based authentication flow.
///
/// Generated class from Pigeon that represents data sent in messages.
struct RunRequest: Hashable {
  /// Unique identifier for this redirect operation.
  ///
  /// Used to correlate the request with its callback, enabling
  /// multiple concurrent redirect flows.
  var nonce: String
  var url: String
  var callback: CallbackConfigMessage
  var preferEphemeral: Bool
  var timeoutMillis: Int64? = nil
  /// Additional HTTP headers to set on the initial URL load.
  ///
  /// Maps to `ASWebAuthenticationSession.additionalHeaderFields`.
  /// Requires iOS 17.4+ / macOS 14.4+. Ignored on older OS versions.
  var additionalHeaderFields: [String?: String?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> RunRequest? {
    let nonce = pigeonVar_list[0] as! String
    let url = pigeonVar_list[1] as! String
    let callback = pigeonVar_list[2] as! CallbackConfigMessage
    let preferEphemeral = pigeonVar_list[3] as! Bool
    let timeoutMillis: Int64? = nilOrValue(pigeonVar_list[4])
    let additionalHeaderFields: [String?: String?]? = nilOrValue(pigeonVar_list[5])

    return RunRequest(
      nonce: nonce,
      url: url,
      callback: callback,
      preferEphemeral: preferEphemeral,
      timeoutMillis: timeoutMillis,
      additionalHeaderFields: additionalHeaderFields
    )
  }
  func toList() -> [Any?] {
    return [
      nonce,
      url,
      callback,
      preferEphemeral,
      timeoutMillis,
      additionalHeaderFields,
    ]
  }
  static func == (lhs: RunRequest, rhs: RunRequest) -> Bool {
    return deepEqualsMessages(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashMessages(value: toList(), hasher: &hasher)
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return CallbackType(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return CallbackConfigMessage.fromList(self.readValue() as! [Any?])
    case 131:
      return RunRequest.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? CallbackType {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? CallbackConfigMessage {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? RunRequest {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Host API for redirect operations on Darwin (iOS/macOS).
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol RedirectHostApi {
  /// Starts a redirect flow and returns the callback URL, or null if cancelled.
  func run(request: RunRequest, completion: @escaping (Result<String?, Error>) -> Void)
  /// Cancels the redirect flow identified by [nonce].
  ///
  /// If [nonce] is empty, cancels all pending operations.
  func cancel(nonce: String) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class RedirectHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `RedirectHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: RedirectHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Starts a redirect flow and returns the callback URL, or null if cancelled.
    let runChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.redirect_darwin.RedirectHostApi.run\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      runChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! RunRequest
        api.run(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      runChannel.setMessageHandler(nil)
    }
    /// Cancels the redirect flow identified by [nonce].
    ///
    /// If [nonce] is empty, cancels all pending operations.
    let cancelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.redirect_darwin.RedirectHostApi.cancel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nonceArg = args[0] as! String
        do {
          try api.cancel(nonce: nonceArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelChannel.setMessageHandler(nil)
    }
  }
}
