// Autogenerated from Pigeon (v26.1.7), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, omit_obvious_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}
bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
        .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length && a.entries.every((MapEntry<Object?, Object?> entry) =>
        (b as Map<Object?, Object?>).containsKey(entry.key) &&
        _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}


/// The type of callback URL matching to use.
enum CallbackType {
  /// Match by custom URL scheme (e.g., `myapp://...`).
  customScheme,
  /// Match by HTTPS host and path (Universal Links).
  https,
}

/// Configuration for how to match callback URLs.
class CallbackConfigMessage {
  CallbackConfigMessage({
    required this.type,
    this.scheme,
    this.host,
    this.path,
  });

  /// The type of callback matching.
  CallbackType type;

  /// The custom URL scheme (for [CallbackType.customScheme]).
  String? scheme;

  /// The HTTPS host (for [CallbackType.https]).
  String? host;

  /// The HTTPS path (for [CallbackType.https]).
  String? path;

  List<Object?> _toList() {
    return <Object?>[
      type,
      scheme,
      host,
      path,
    ];
  }

  Object encode() {
    return _toList();  }

  static CallbackConfigMessage decode(Object result) {
    result as List<Object?>;
    return CallbackConfigMessage(
      type: result[0]! as CallbackType,
      scheme: result[1] as String?,
      host: result[2] as String?,
      path: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! CallbackConfigMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Request to start a redirect-based authentication flow.
class RunRequest {
  RunRequest({
    required this.nonce,
    required this.url,
    required this.callback,
    required this.preferEphemeral,
    this.timeoutMillis,
    this.additionalHeaderFields,
  });

  /// Unique identifier for this redirect operation.
  ///
  /// Used to correlate the request with its callback, enabling
  /// multiple concurrent redirect flows.
  String nonce;

  String url;

  CallbackConfigMessage callback;

  bool preferEphemeral;

  int? timeoutMillis;

  /// Additional HTTP headers to set on the initial URL load.
  ///
  /// Maps to `ASWebAuthenticationSession.additionalHeaderFields`.
  /// Requires iOS 17.4+ / macOS 14.4+. Ignored on older OS versions.
  Map<String?, String?>? additionalHeaderFields;

  List<Object?> _toList() {
    return <Object?>[
      nonce,
      url,
      callback,
      preferEphemeral,
      timeoutMillis,
      additionalHeaderFields,
    ];
  }

  Object encode() {
    return _toList();  }

  static RunRequest decode(Object result) {
    result as List<Object?>;
    return RunRequest(
      nonce: result[0]! as String,
      url: result[1]! as String,
      callback: result[2]! as CallbackConfigMessage,
      preferEphemeral: result[3]! as bool,
      timeoutMillis: result[4] as int?,
      additionalHeaderFields: (result[5] as Map<Object?, Object?>?)?.cast<String?, String?>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RunRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is CallbackType) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is CallbackConfigMessage) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is RunRequest) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final value = readValue(buffer) as int?;
        return value == null ? null : CallbackType.values[value];
      case 130: 
        return CallbackConfigMessage.decode(readValue(buffer)!);
      case 131: 
        return RunRequest.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Host API for redirect operations on Darwin (iOS/macOS).
class RedirectHostApi {
  /// Constructor for [RedirectHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  RedirectHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Starts a redirect flow and returns the callback URL, or null if cancelled.
  Future<String?> run(RunRequest request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.redirect_darwin.RedirectHostApi.run$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as String?);
    }
  }

  /// Cancels the redirect flow identified by [nonce].
  ///
  /// If [nonce] is empty, cancels all pending operations.
  Future<void> cancel(String nonce) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.redirect_darwin.RedirectHostApi.cancel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[nonce]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}
